{% set version = "0.24.0" %}

package:
  name: simpeg
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/S/SimPEG/simpeg-{{ version }}.tar.gz
  sha256: 420dc4b4684a4c0092ff605b2a56d6884335585d3bedd51430875e0024deebf3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >=3.10
    - numpy >=1.22
    - scipy >=1.8
    - pymatsolver >=0.3
    - matplotlib-base
    - discretize >=0.11
    - geoana >=0.7.0
    - libdlf
  run_constrained:
    - choclo >=0.3.0
    - fsspec >=0.3.3
    - scikit-learn >=1.2

test:
  imports:
    - simpeg
    - simpeg.electromagnetics
    - simpeg.electromagnetics.analytics
    - simpeg.electromagnetics.frequency_domain
    - simpeg.electromagnetics.natural_source
    - simpeg.electromagnetics.natural_source.utils
    - simpeg.electromagnetics.static
    - simpeg.electromagnetics.static.resistivity
    - simpeg.electromagnetics.static.induced_polarization
    - simpeg.electromagnetics.static.spectral_induced_polarization
    - simpeg.electromagnetics.static.utils
    - simpeg.electromagnetics.time_domain
    - simpeg.electromagnetics.utils
    - simpeg.electromagnetics.viscous_remanent_magnetization
    - simpeg.flow
    - simpeg.flow.richards
    - simpeg.potential_fields
    - simpeg.potential_fields.gravity
    - simpeg.potential_fields.magnetics
    - simpeg.seismic
    - simpeg.seismic.straight_ray_tomography
    - simpeg.utils
    - simpeg.utils.drivers
    - simpeg.regularization
    - simpeg.meta

about:
  home: http://simpeg.xyz/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SimPEG: Simulation and Parameter Estimation in Geophysics'

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
    - santisoler
