{% set version = "0.20.0" %}

package:
  name: simpeg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SimPEG/SimPEG-{{ version }}.tar.gz
  sha256: 9798031b19c0be04f84a974f66a9595c560d903e2d90bf5587fe3a7c138e1e32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - scipy >=1.8
    - scikit-learn >=1.2
    - pymatsolver >=0.2
    - matplotlib-base
    - discretize >=0.8
    - geoana >=0.4.0
    - empymod >=2.0.0
    - pandas
    - utm

test:
  imports:
    - SimPEG
    - SimPEG.electromagnetics
    - SimPEG.electromagnetics.analytics
    - SimPEG.electromagnetics.frequency_domain
    - SimPEG.electromagnetics.natural_source
    - SimPEG.electromagnetics.natural_source.utils
    - SimPEG.electromagnetics.static
    - SimPEG.electromagnetics.static.resistivity
    - SimPEG.electromagnetics.static.induced_polarization
    - SimPEG.electromagnetics.static.spectral_induced_polarization
    - SimPEG.electromagnetics.static.utils
    - SimPEG.electromagnetics.time_domain
    - SimPEG.electromagnetics.utils
    - SimPEG.electromagnetics.viscous_remanent_magnetization
    - SimPEG.flow
    - SimPEG.flow.richards
    - SimPEG.potential_fields
    - SimPEG.potential_fields.gravity
    - SimPEG.potential_fields.magnetics
    - SimPEG.seismic
    - SimPEG.seismic.straight_ray_tomography
    - SimPEG.utils
    - SimPEG.utils.drivers
    - SimPEG.regularization
    - SimPEG.meta

about:
  home: http://simpeg.xyz/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SimPEG: Simulation and Parameter Estimation in Geophysics'

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
