{% set version = "0.13.0" %}

package:
  name: simpeg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SimPEG/SimPEG-{{ version }}.tar.gz
  sha256: 0d12d350f8f23bd849aba84ddb82ff6d39976f042c3a427c691eb2b1072d95b5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cython
    - discretize >=0.4.0
    - geoana >=0.0.4
    - ipython
    - matplotlib
    - numpy >=1.7
    - properties >=0.5.2
    - pymatsolver >=0.1.1
    - scipy >=0.13
    - vectormath >=0.2.0

test:
  imports:
    - SimPEG
    - SimPEG.DC
    - SimPEG.EM
    - SimPEG.EM.Analytics
    - SimPEG.EM.FDEM
    - SimPEG.EM.NSEM
    - SimPEG.EM.NSEM.Utils
    - SimPEG.EM.Static
    - SimPEG.EM.Static.DC
    - SimPEG.EM.Static.IP
    - SimPEG.EM.Static.SIP
    - SimPEG.EM.Static.SP
    - SimPEG.EM.Static.Utils
    - SimPEG.EM.TDEM
    - SimPEG.EM.Utils
    - SimPEG.FLOW
    - SimPEG.FLOW.Richards
    - SimPEG.IP
    - SimPEG.NSEM
    - SimPEG.PF
    - SimPEG.SEIS
    - SimPEG.SEIS.StraightRay
    - SimPEG.SIP
    - SimPEG.Utils
    - SimPEG.VRM
    - SimPEG.regularization

about:
  home: http://simpeg.xyz/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "SimPEG: Simulation and Parameter Estimation in Geophysics"

extra:
  recipe-maintainers:
    - lheagy
