{% set version = "0.15.2" %}

package:
  name: simpeg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SimPEG/SimPEG-{{ version }}.tar.gz
  sha256: 6df3335e8d27dff2d286b4eed81cced7adb7fbabcaba77be0523401afae19d7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.7
    - scipy >=1.0.0
    - scikit-learn >=0.22
    - pymatsolver >=0.1.1
    - matplotlib-base
    - properties >=0.5.2
    - vectormath >=0.2.0
    - discretize >=0.7.0
    - geoana >=0.0.4
    - empymod
    - pandas

test:
  imports:
    - SimPEG
    - SimPEG.electromagnetics
    - SimPEG.electromagnetics.analytics
    - SimPEG.electromagnetics.frequency_domain
    - SimPEG.electromagnetics.natural_source
    - SimPEG.electromagnetics.natural_source.utils
    - SimPEG.electromagnetics.static
    - SimPEG.electromagnetics.static.resistivity
    - SimPEG.electromagnetics.static.induced_polarization
    - SimPEG.electromagnetics.static.spectral_induced_polarization
    - SimPEG.electromagnetics.static.utils
    - SimPEG.electromagnetics.time_domain
    - SimPEG.electromagnetics.utils
    - SimPEG.electromagnetics.viscous_remanent_magnetization
    - SimPEG.flow
    - SimPEG.flow.richards
    - SimPEG.potential_fields
    - SimPEG.potential_fields.gravity
    - SimPEG.potential_fields.magnetics
    - SimPEG.seismic
    - SimPEG.seismic.straight_ray_tomography
    - SimPEG.utils
    - SimPEG.utils.drivers
    - SimPEG.regularization

about:
  home: http://simpeg.xyz/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SimPEG: Simulation and Parameter Estimation in Geophysics'

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
    - thast
