{% set version = "0.21.1" %}

package:
  name: simpeg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SimPEG/SimPEG-{{ version }}.tar.gz
  sha256: e71c32770a9c3a32b84033d16adacf10bb5357b31dcd7ae5beab7d59f240bf5e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy >=1.20
    - scipy >=1.8
    - scikit-learn >=1.2
    - pymatsolver-base >=0.2
    - matplotlib-base
    - discretize >=0.10
    - geoana >=0.5.0
    - empymod >=2.0.0
    - pandas

test:
  imports:
    - SimPEG
    - SimPEG.electromagnetics
    - SimPEG.electromagnetics.analytics
    - SimPEG.electromagnetics.frequency_domain
    - SimPEG.electromagnetics.natural_source
    - SimPEG.electromagnetics.natural_source.utils
    - SimPEG.electromagnetics.static
    - SimPEG.electromagnetics.static.resistivity
    - SimPEG.electromagnetics.static.induced_polarization
    - SimPEG.electromagnetics.static.spectral_induced_polarization
    - SimPEG.electromagnetics.static.utils
    - SimPEG.electromagnetics.time_domain
    - SimPEG.electromagnetics.utils
    - SimPEG.electromagnetics.viscous_remanent_magnetization
    - SimPEG.flow
    - SimPEG.flow.richards
    - SimPEG.potential_fields
    - SimPEG.potential_fields.gravity
    - SimPEG.potential_fields.magnetics
    - SimPEG.seismic
    - SimPEG.seismic.straight_ray_tomography
    - SimPEG.utils
    - SimPEG.utils.drivers
    - SimPEG.regularization
    - SimPEG.meta

about:
  home: http://simpeg.xyz/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SimPEG: Simulation and Parameter Estimation in Geophysics'

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
