{% set version = "0.14.2" %}

package:
  name: simpeg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SimPEG/SimPEG-{{ version }}.tar.gz
  sha256: 088fb594c424186eda1f9189e340b4ad95b997178da90d8a8e510a614bf8aeed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.7
    - scipy >=0.13
    - pymatsolver >=0.1.1
    - matplotlib-base
    - properties >=0.5.2
    - vectormath >=0.2.0
    - discretize >=0.4.0
    - geoana >=0.0.4
    - empymod
    - pandas

test:
  imports:
    - SimPEG
    - SimPEG.electromagnetics
    - SimPEG.electromagnetics.analytics
    - SimPEG.electromagnetics.frequency_domain
    - SimPEG.electromagnetics.natural_source
    - SimPEG.electromagnetics.natural_source.utils
    - SimPEG.electromagnetics.static
    - SimPEG.electromagnetics.static.resistivity
    - SimPEG.electromagnetics.static.induced_polarization
    - SimPEG.electromagnetics.static.spectral_induced_polarization
    - SimPEG.electromagnetics.static.utils
    - SimPEG.electromagnetics.time_domain
    - SimPEG.electromagnetics.utils
    - SimPEG.electromagnetics.viscous_remanent_magnetization
    - SimPEG.flow
    - SimPEG.flow.richards
    - SimPEG.potential_fields
    - SimPEG.potential_fields.gravity
    - SimPEG.potential_fields.magnetics
    - SimPEG.seismic
    - SimPEG.seismic.straight_ray_tomography
    - SimPEG.utils
    - SimPEG.utils.drivers
    - SimPEG.regularization

about:
  home: http://simpeg.xyz/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SimPEG: Simulation and Parameter Estimation in Geophysics'

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
    - thast
